### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by ghost** [Gummibeer/a3l-webinterface#13]
wird an dem panel noch aktiv gearbeitet?

**Comment by Gummibeer** [comment]
In current state not cause it isn't used on any server. But if you want/need something I will try to put it in.

**Comment by ghost** [comment]
i need an Webpanel for my Altis life server but many doesnt work or arent easy to use

**Comment by ghost** [comment]
and how to install it :D

**Comment by Gummibeer** [comment]
It's a laravel project - so you need basic/medium knowledge in php, composer and laravel - this version is tailored to the old Pyro-Life Server - so it could be that you have to adjust some parts (configs, database) and possibly also remove whole moduls if your server doesn't support these things or you don't want them.

In addition to this: this application is primary made for your whole community - it includes a message system, forum, lotto, statistics, profiles and so on. If you just want something for you or your Supporters to simplify some database actions this application is too overpowered.

**Comment by ghost** [comment]
can you make an Tool only for me and my supporters

**Comment by Gummibeer** [comment]
I can but have not much time atm. And if it's just for your supporters and you you can simply use the mysql database directly with HeidiSQL or Navicat or any other DB client. with the right SQL Userconfiguration you can prevent that they have access to tables they don't need and with some simple database triggers you can add logs for actions by your supporters.
Or you learn a bit of php and laravel and adjust the parts you don't need.

**Comment by ghost** [comment]
Is laravel an host for websites or like php?

**Comment by ghost** [comment]
Or I need to install WordPress and add then user there or how

**Comment by Gummibeer** [comment]
Laravel is a php framework - you can create whatever you want with it. Wordpress is part of this current application cause of the blog and static pages.
Cause of the customized database you will have to configure a lot and adjust/remove some database column names in the application.
